---
- name: Install Docker and Python on AWS EC2 Ubuntu
  hosts: aws_ec2
  become: true # This will use sudo before running commands
  vars:
    arch_mapping: # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      # aarch64: arm64 # ARM64 architecture if you are using AWS Graviton instances

  tasks:
    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist # Upgrade all packages to the latest version
        cache_valid_time: 3600 # Update the cache every 3600 seconds (1 hour)

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common

    - name: Create directory for Docker's GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Print architecture variables
      ansible.builtin.debug:
        msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}"

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        filename: docker
        state: present

    - name: Install Docker and related packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Enable and start Docker services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service

    - name: Install Git (required for cloning repository)
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: true

    - name: Install Python3 and pip (for potential Python dependencies)
      ansible.builtin.apt:
        pkg:
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Create project directory
      ansible.builtin.file:
        path: /opt/poneglyph-reduce
        state: directory
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Clone Poneglyph-Reduce repository
      ansible.builtin.git:
        repo: https://github.com/Youngermaster/Poneglyph-Reduce.git
        dest: /opt/poneglyph-reduce
        clone: true
        update: true
        force: true
      become_user: "{{ ansible_user }}"

    - name: Set correct ownership for the repository
      ansible.builtin.file:
        path: /opt/poneglyph-reduce
        state: directory
        recurse: true
        owner: "{{ ansible_user }}"
        group: docker
        mode: "0755"

    - name: Make run.sh executable
      ansible.builtin.file:
        path: /opt/poneglyph-reduce/run.sh
        mode: "0755"
        state: file
      ignore_errors: true

    - name: Display setup completion message
      ansible.builtin.debug:
        msg: |
          ========================================
          🎉 EC2 Setup Complete! 🎉
          ========================================
          ✅ Docker installed and running
          ✅ Repository cloned to /opt/poneglyph-reduce
          ✅ User {{ ansible_user }} added to docker group

          Next steps:
          1. SSH to your EC2 instance
          2. cd /opt/poneglyph-reduce
          3. Run: docker compose up --build --scale worker=3 -d
          4. Access the dashboard at http://<EC2_PUBLIC_IP>:3000

          Note: You may need to log out and back in for docker group changes to take effect.
          ========================================
